server:
  port: 8081
spring:
  application:
    name: bar-service
  security:
    user:
      name: bar
      password: password

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
