server:
  port: 9999
spring:
  application:
    name: spring-boot-admin
  security:
    user:
      name: admin
      password: password

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/